apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: 383265273024.dkr.ecr.us-east-1.amazonaws.com/my-node-app:my-node-app:v1
          ports:
            - containerPort: 3000
